---

stages:
  - build
  - deploy

variables:
  RTSOPTS: "+RTS -N1 -s"
  STACK_ROOT: ${CI_PROJECT_DIR}/.stack-work

build:
  stage: build
  except:
    - tags
  image:
    name: frankhjung/haskell:9.4.7
    entrypoint: [""]
  script:
    - make clean check build test bench doc exec
    - mv $(stack path --local-doc-root)/ public/
    - mv ${STACK_ROOT}/benchmark.html public/
  artifacts:
    paths:
      - public
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
      - ${STACK_ROOT}

pages:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  image: alpine:latest
  script:
    - echo Publishing documentation ...
  dependencies:
    - build
  artifacts:
    paths:
      - public
