stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_NAME}
  paths:
    - .stack
    - .stack-work

variables:
  RTSOPTS: "+RTS -N1"
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

build:
  except:
    - tags
  image:
    name: frankhjung/haskell:8.6.5
    entrypoint: [""]
  stage: build
  script:
    - make setup clean all

pages:
  only:
    - master
  image: alpine:latest
  stage: deploy
  script:
    - mkdir -p public
    - cp -pr .stack-work/install/x86_64-linux/*/*/hpc/* public/
    - cp -pr .stack-work/dist/x86_64-linux/Cabal-*/doc/html/gcd/* public/
  artifacts:
    paths:
    - public
  only:
    refs:
      - master
