stages:
  - build
  - deploy

cache:
  key: $CI_COMMIT_REF_NAME
  paths:
    - .stack
    - .stack-work

variables:
  RTSOPTS: "+RTS -N1"
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

build:
  image:
    name: frankhjung/haskell:latest
    entrypoint: [""]
  stage: build
  script:
    - make setup clean all

pages:
  image: alpine:latest
  stage: deploy
  script:
    - mkdir -p public
    - cp -pr .stack-work/dist/x86_64-linux/Cabal-*/doc/html/GCD/* public/
  artifacts:
    paths:
    - public
  only:
    refs:
      - master
