---

name: haskell gcd

on:
  push:
  check_run:
    types: [rerequested, requested_action]

jobs:

  build:

    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v1.0.0
        with:
          ref: refs/heads/master
          fetch-depth: 1

      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            .stack/
            .stack-work/
          key: $GITHUB_REF

      - name: stack
        run: |
          stack setup
          stack update
          stack path
          stack query
          stack ls dependencies
          cabal check

      - name: build
        run: stack build --no-test

      - name: test
        run: stack test

      - name: bench
        run: stack bench --benchmark-arguments '-o .stack-work/benchmark.html'

      - name: documentation
        run: stack haddock

      - name: exec
        run: stack exec gcd -- 112 12   # expect 4 4

      - name: copy
        run: |
          mv $(stack path --local-doc-root)/gcd*/ public/
          cp -fp .stack-work/benchmark.html public/

      - name: publish
        uses: crazy-max/ghaction-github-pages@v0.4.0
        if: success()
        with:
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
