name: haskell gcd

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v1.0.0
      with:
        ref: refs/heads/master
        fetch-depth: 1

    - name: stack
      run: |
        curl -sSL https://get.haskellstack.org/ | sh
        stack setup

    - name: build
      run: stack build --pedantic --no-test --ghc-options='-O2'

    - name: test
      run: stack test

    - name: exec
      run: stack exec gcd -- 112 12   # expect 4 4

    - name: documentation
      run: |
        stack test --coverage
        stack haddock

    - name: copy
      run: |
        mkdir -p public
        cp -pr .stack-work/dist/x86_64-linux/Cabal-*/doc/html/gcd/* public/

    - name: publish
      uses: crazy-max/ghaction-github-pages@v0.4.0
      if: success()
      with:
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
